### ISSUE TITLE
Remote shell fails with gpg: signing failed: No secret key

### ISSUE THREAD

**Issue by ravinderrana** [quantopian/PenguinDome#19]
We got client and server running at our end but when we try to use remoteshell from server it's failing with following error:

bin/client_shell test-client
[2020-04-23 08:02:50.571120] INFO: penguindome-client_shell: Requesting remote shell from rana-Latitude-E5450
[2020-04-23 08:02:50.587020] ERROR: penguindome-client_shell: Gpg command ('gpg', '--batch', '--yes', '--quiet', '--trust-model', 'always', '-u', 'penguindome-client', '--armor', '--detach-sign', '-o', '/tmp/tmp4pyaqfer', '/tmp/tmprup6wkf6') failed. Output:
gpg: skipped "penguindome-client": No secret key
gpg: signing failed: No secret key

Traceback (most recent call last):
  File "/root/PenguinDome/penguindome/penguindome.py", line 152, in gpg_command
    return subprocess.check_output(cmd, stderr=subprocess.STDOUT).\
  File "/usr/local/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('gpg', '--batch', '--yes', '--quiet', '--trust-model', 'always', '-u', 'penguindome-client', '--armor', '--detach-sign', '-o', '/tmp/tmp4pyaqfer', '/tmp/tmprup6wkf6')' returned non-zero exit status 2
Traceback (most recent call last):
  File "/root/PenguinDome/server/client_shell.py", line 58, in <module>
    main()

Both the client and server are running Ubuntu 18.04.

Can someone please help? We are not sure what we are missing. 

Thanks

**Comment by jikamens** [comment]
I know why this is happening and I'm working on a fix.

**Comment by jikamens** [comment]
PR for this bug submitted in quantopian/PenguinDome#20.

**Comment by ravinderrana** [comment]
Thanks a lot @jikamens , the PR indeed fixes the issue.
